using Microsoft.AspNetCore.Mvc;
using HamroPharma.API.Models.Domains;
using HamroPharma.API.Models.DTO;
using HamroPharma.API.Repositories.Interface;
using System;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using HamroPharma.API.Data;
using HamroPharma.API.Repositories.Implementation;
using Microsoft.AspNetCore.Http.HttpResults;
using HamroPharma.API.Models.DTOs;

namespace HamroPharma.API.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ProductController : ControllerBase
    {
        private readonly IProductRepository _productRepository;

        public ProductController(IProductRepository productRepository)
        {
            _productRepository = productRepository;
        }

        // GET: api/products
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Products>>> GetAllProducts()
        {
            try
            {
                var products = await _productRepository.GetAllAysnc();
                return Ok(products);
            }
            catch
            {
                return StatusCode(500, "Failed to retrieve products");
            }
        }

        // POST: api/products
        [HttpPost]
        public async Task<ActionResult<Products>> AddProduct(ProductDto productDto)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                var product = new Products
                {
                    Id = Guid.NewGuid(), // Assuming Id is generated by the database, so generating a new Guid here
                    Name = productDto.Name,
                    Description = productDto.Description,
                    Quantity = productDto.Quantity,
                    CreatedDate = productDto.CreatedDate,
                    Price = productDto.Price,
                    ExpiryDate = productDto.ExpiryDate
                };

                var addedProduct = await _productRepository.AddProduct(product);
                return CreatedAtAction(nameof(GetProduct), new { id = addedProduct.Id }, addedProduct);
            }
            catch
            {
                return StatusCode(500, "Failed to add the product");
            }
        }
        // GET: api/products/{id}
        [HttpGet("{id}")]
        public async Task<ActionResult<Products>> GetProduct(Guid id)
        {
            var product = await _productRepository.GetProductById(id);

            if (product == null)
            {
                return NotFound();
            }

            return Ok(product);
        }
    }
}

